language: csharp
solution: ./src/JitterMagic.sln
install:
  - nuget restore ./src/JitterMagic.sln
  - nuget install xunit.runner.console -Prerelease -Version 2.1.0-beta4-build3109 -OutputDirectory testrunner -Source https://www.myget.org/F/xunit/
script:
  - xbuild /p:Configuration=Release ./src/JitterMagic.sln
  #- mono ./testrunner/xunit.runner.console.2.1.0-beta4-build3109/tools/xunit.console.exe ./src/JitterMagic.UnitTests/bin/Release/JitterMagic.UnitTests.dll -noappdomain