#---------------------------------#
#      general configuration      #
#---------------------------------#

version: 1.0.5.{build}

pull_requests:  
  do_not_increment_build_number: true

skip_tags: true

#---------------------------------#
#    environment configuration    #
#---------------------------------#

image: Visual Studio 2015

clone_depth: 1

nuget:  
  disable_publish_on_pr: true

#---------------------------------#
#       build configuration       #
#---------------------------------#

configuration: Release

build_script:
- dotnet --info
- dotnet restore --no-cache
- dotnet build **/project.json --configuration Release --version-suffix %APPVEYOR_BUILD_NUMBER%
- dotnet pack src/JitterMagic/project.json --configuration Release --version-suffix %APPVEYOR_BUILD_NUMBER% --no-build

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test_script:
- dotnet test test/JitterMagic.UnitTests/project.json --configuration Release --no-build

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
- path: src/**/*.nupkg

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy: off  